### ISSUE TITLE
what content should be responsed from the auth server

### ISSUE THREAD

**Issue by sayid** [FlyingShit-XinHuang/kong-auth-demo#1]
excuse me.
if the token is error or timeout，what content should be responsed from the auth server。

**Comment by FlyingShit-XinHuang** [comment]
@sayid 
It's defined in function query_and_validate_token of handler.lua 

The status code(200) is checked for successful response.
The '.expires_in' field of response body (JSON encoded) is used to calculate how long the token will be valid.

**Comment by FlyingShit-XinHuang** [comment]
@sayid 
It's a demo project for memo initially. Sorry for poorly documented.
May it would be helpful to you.

**Comment by sayid** [comment]
ok!,thank you very much!
